redirectsOrigin = "config"
headers = []

[functions]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"

[plugins.inputs]

[build]
publish = "/Users/stephen/Documents/DoctorPro/bible3dsphere/emotion-sphere-ui/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/stephen/Documents/DoctorPro/bible3dsphere/emotion-sphere-ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "/404"
status = 404.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]